FROM alpine
ARG TARGETPLATFORM \
    TARGETOS \
    TARGETARCH \
    TARGETVARIANT \
    BUILDPLATFORM \
    BUILDOS \
    BUILDARCH \
    BUILDVARIANT

RUN echo -e "TARGETPLATFORM=${TARGETPLATFORM}\nTARGETOS=${TARGETOS}\nTARGETARCH=${TARGETARCH}\nTARGETVARIANT=${TARGETVARIANT}\nBUILDPLATFORM=${BUILDPLATFORM}\nBUILDOS=${BUILDOS}\nBUILDARCH=${BUILDARCH}\nBUILDVARIANT=$BUILDVARIANT"
